import React, { useState, useEffect, useRef } from 'react';
import { initializeApp } from 'firebase/app';
import { getAuth, onAuthStateChanged, signInAnonymously, signInWithCustomToken } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';
import { 
  Camera, Upload, Sparkles, RefreshCw, Sun, Check, 
  Palette, Droplets, Download, Layers, X, Paintbrush, Zap, Play
} from 'lucide-react';
gradlew assembleDebug
// --- Firebase Initialization ---
const firebaseConfig = JSON.parse(__firebase_config);
const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);
const appId = typeof __app_id !== 'undefined' ? __app_id : 'sun-style-aqua-opt';

const App = () => {
  const [user, setUser] = useState(null);
  const [sourceFile, setSourceFile] = useState(null);
  const [previewUrl, setPreviewUrl] = useState(null);
  const [resultImage, setResultImage] = useState(null);
  const [bulkResults, setBulkResults] = useState([]); // Array for bulk storage
  const [isProcessing, setIsProcessing] = useState(false);
  const [error, setError] = useState(null);
  
  // Settings
  const [style, setStyle] = useState('dress');
  const [colorTheme, setColorTheme] = useState('multicolor');
  const [isWetLook, setIsWetLook] = useState(false);
  const [isBulkMode, setIsBulkMode] = useState(false);
  const [status, setStatus] = useState("");

  const apiKey = ""; 

  useEffect(() => {
    const initAuth = async () => {
      if (typeof __initial_auth_token !== 'undefined' && __initial_auth_token) {
        await signInWithCustomToken(auth, __initial_auth_token);
      } else {
        await signInAnonymously(auth);
      }
    };
    initAuth();
    return onAuthStateChanged(auth, setUser);
  }, []);

  const handleFileUpload = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    if (file.size > 4 * 1024 * 1024) {
      setError("File too large (>4MB)");
      return;
    }
    if (previewUrl) URL.revokeObjectURL(previewUrl);
    setSourceFile(file);
    setPreviewUrl(URL.createObjectURL(file));
    setResultImage(null);
    setBulkResults([]);
    setError(null);
  };

  const toBase64 = (file) => new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve(reader.result.split(',')[1]);
    reader.onerror = error => reject(error);
  });

  const generateSingle = async (base64, theme) => {
    const prompt = `STYLING: Replace ALL clothing with a ${theme} ${style === 'bikini' ? 'thin American string bikini' : 'modern sun dress'}. 
    ${style === 'bikini' ? 'MANDATORY: Use ultra-thin straps and minimal American-cut coverage.' : ''}
    ${isWetLook ? 'WET EFFECT: Hair must be drenched/matted. Clothes soaked/translucent. Skin glossy with droplets.' : ''}
    Maintain person identity and background. High-end fashion photography style.`;

    const payload = {
      contents: [{
        parts: [{ text: prompt }, { inlineData: { mimeType: "image/png", data: base64 } }]
      }],
      generationConfig: { responseModalities: ['IMAGE'] }
    };

    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image-preview:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });

    if (!response.ok) throw new Error(`Failed for ${theme}`);
    const result = await response.json();
    const imgData = result.candidates?.[0]?.content?.parts?.find(p => p.inlineData)?.inlineData?.data;
    return imgData ? { theme, url: `data:image/png;base64,${imgData}` } : null;
  };

  const runSynthesis = async () => {
    if (!sourceFile || isProcessing) return;
    setIsProcessing(true);
    setError(null);
    setBulkResults([]);
    setStatus(isBulkMode ? "Turbo Multi-Processing..." : "Converting...");

    try {
      const base64Data = await toBase64(sourceFile);
      
      if (isBulkMode) {
        // Parallel requests for speed
        const themes = ['multicolor', 'white', 'black'];
        const promises = themes.map(t => generateSingle(base64Data, t));
        const results = await Promise.all(promises);
        const validResults = results.filter(r => r !== null);
        setBulkResults(validResults);
        if (validResults.length > 0) setResultImage(validResults[0].url);
      } else {
        const res = await generateSingle(base64Data, colorTheme);
        if (res) setResultImage(res.url);
      }
    } catch (err) {
      setError(err.message);
    } finally {
      setIsProcessing(false);
      setStatus("");
    }
  };

  return (
    <div className="min-h-screen bg-[#080808] text-white font-sans antialiased overflow-x-hidden">
      <div className="max-w-6xl mx-auto p-4 md:p-8">
        
        <header className="flex justify-between items-center mb-8">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-blue-600 rounded-xl shadow-lg shadow-blue-500/20">
              <Zap size={20} className="fill-current text-white" />
            </div>
            <h1 className="text-xl font-black tracking-tight uppercase italic">SunStyle <span className="text-blue-500">Turbo</span></h1>
          </div>
          <div className="flex items-center gap-4">
            <button 
              onClick={() => setIsBulkMode(!isBulkMode)}
              className={`text-[10px] font-black uppercase px-4 py-2 rounded-full border transition-all ${isBulkMode ? 'bg-orange-500 border-orange-400 text-white shadow-lg' : 'border-white/10 text-white/40'}`}
            >
              {isBulkMode ? '⚡ Bulk Turbo ON' : 'Single Shot'}
            </button>
            {previewUrl && (
              <button onClick={() => {setPreviewUrl(null); setResultImage(null); setSourceFile(null); setBulkResults([]);}} className="text-[10px] font-bold opacity-40 hover:opacity-100 uppercase tracking-widest">Reset</button>
            )}
          </div>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          <div className="lg:col-span-4 space-y-4">
            <div className="bg-white/5 border border-white/10 rounded-3xl p-5 space-y-6">
              {/* Upload */}
              <div 
                onClick={() => !isProcessing && document.getElementById('file-up').click()}
                className={`relative h-32 rounded-2xl border-2 border-dashed flex flex-col items-center justify-center cursor-pointer transition-all ${previewUrl ? 'border-blue-500/50 bg-blue-500/5' : 'border-white/10 hover:border-white/20'}`}
              >
                {previewUrl ? (
                  <img src={previewUrl} className="absolute inset-0 w-full h-full object-cover rounded-2xl opacity-40" alt="Preview" />
                ) : (
                  <Upload className="text-white/20" />
                )}
                <span className="relative text-[10px] font-bold uppercase mt-2 text-white/60">Upload Image</span>
                <input id="file-up" type="file" className="hidden" onChange={handleFileUpload} />
              </div>

              {/* Toggles */}
              <div className="space-y-4">
                <div className="grid grid-cols-2 gap-2">
                  <button onClick={() => setStyle('dress')} className={`py-2 rounded-xl text-[10px] font-black uppercase border transition-all ${style === 'dress' ? 'bg-white text-black border-white' : 'border-white/10 text-white/40'}`}>Sun Dress</button>
                  <button onClick={() => setStyle('bikini')} className={`py-2 rounded-xl text-[10px] font-black uppercase border transition-all ${style === 'bikini' ? 'bg-white text-black border-white' : 'border-white/10 text-white/40'}`}>Thin Bikini</button>
                </div>

                {!isBulkMode && (
                  <div className="flex gap-1 bg-black/40 p-1 rounded-xl">
                    {['multicolor', 'white', 'black'].map(c => (
                      <button key={c} onClick={() => setColorTheme(c)} className={`flex-1 py-1.5 rounded-lg text-[9px] font-black uppercase transition-all ${colorTheme === c ? 'bg-white/10 text-white' : 'text-white/30'}`}>{c}</button>
                    ))}
                  </div>
                )}

                <button 
                  onClick={() => setIsWetLook(!isWetLook)}
                  className={`w-full py-3 rounded-xl border flex items-center justify-center gap-2 transition-all ${isWetLook ? 'bg-blue-600/20 border-blue-500 text-blue-400' : 'border-white/10 text-white/40'}`}
                >
                  <Droplets size={14} />
                  <span className="text-[10px] font-black uppercase">Wet Look: {isWetLook ? 'ON' : 'OFF'}</span>
                </button>
              </div>
            </div>

            <button
              onClick={runSynthesis}
              disabled={!previewUrl || isProcessing}
              className={`w-full py-5 rounded-2xl font-black uppercase tracking-widest text-sm transition-all shadow-xl flex items-center justify-center gap-3 ${
                !previewUrl || isProcessing 
                ? 'bg-white/5 text-white/20' 
                : 'bg-white text-black hover:scale-[1.02] active:scale-95'
              }`}
            >
              {isProcessing ? <RefreshCw className="animate-spin" size={20} /> : (isBulkMode ? <><Sparkles size={20} /> Multi-Tap Bulk</> : <><Play size={20} /> Single Generate</>)}
            </button>
            {status && <p className="text-center text-[10px] text-blue-500 font-bold uppercase animate-pulse">{status}</p>}
          </div>

          <div className="lg:col-span-8 space-y-6">
            <div className="bg-black border border-white/5 rounded-[40px] overflow-hidden min-h-[500px] flex flex-col relative">
              <div className="flex flex-col md:flex-row h-full flex-grow">
                {/* Source View */}
                <div className={`relative flex-1 flex items-center justify-center p-6 ${resultImage ? 'md:border-r border-white/5 bg-black' : ''}`}>
                  {!previewUrl ? <Layers className="opacity-5" size={48} /> : <img src={previewUrl} className="max-w-full max-h-[450px] object-contain rounded-xl shadow-2xl" alt="Ref" />}
                  <div className="absolute top-6 left-6 text-[9px] font-black opacity-20 uppercase tracking-widest">Input Layer</div>
                </div>

                {/* Main Output */}
                {resultImage ? (
                  <div className="relative flex-1 flex items-center justify-center p-6 bg-white/[0.02] animate-in fade-in duration-500">
                    <img src={resultImage} className="max-w-full max-h-[450px] object-contain rounded-xl shadow-2xl" alt="Result" />
                    <button 
                      onClick={() => { const link = document.createElement('a'); link.href = resultImage; link.download = 'style.png'; link.click(); }}
                      className="absolute bottom-6 right-6 bg-white text-black p-3 rounded-xl hover:bg-blue-500 hover:text-white transition-all shadow-xl"
                    >
                      <Download size={18} />
                    </button>
                  </div>
                ) : (
                  previewUrl && isProcessing && (
                    <div className="flex-1 flex flex-col items-center justify-center">
                      <div className="w-10 h-10 border-2 border-orange-500 border-t-transparent rounded-full animate-spin mb-4" />
                      <span className="text-[10px] font-bold uppercase tracking-widest opacity-40 italic">Generating Excellence...</span>
                    </div>
                  )
                )}
              </div>
            </div>

            {/* Bulk Gallery */}
            {bulkResults.length > 0 && (
              <div className="grid grid-cols-3 gap-4 animate-in slide-in-from-bottom-4 duration-700">
                {bulkResults.map((res, i) => (
                  <div 
                    key={i} 
                    onClick={() => setResultImage(res.url)}
                    className={`relative aspect-[3/4] bg-white/5 rounded-2xl overflow-hidden border-2 cursor-pointer transition-all hover:scale-[1.05] ${resultImage === res.url ? 'border-blue-500 shadow-lg shadow-blue-500/20' : 'border-transparent'}`}
                  >
                    <img src={res.url} className="w-full h-full object-cover" alt={res.theme} />
                    <div className="absolute bottom-0 inset-x-0 bg-gradient-to-t from-black/80 p-2">
                      <span className="text-[8px] font-black uppercase tracking-widest">{res.theme}</span>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
      {error && <div className="fixed bottom-8 left-1/2 -translate-x-1/2 bg-red-500 text-white px-6 py-3 rounded-2xl font-black uppercase text-xs shadow-2xl z-50 flex gap-4 items-center"><span>{error}</span><X size={16} onClick={() => setError(null)} className="cursor-pointer" /></div>}
    </div>
  );
};

export default App;
